local t = dofile('tests/mame.lua')('breakout', 'tools/controls.lua')
local left, right = t.field('keyb_special',16), t.field('keyb_special',32)
local shift, space = t.field('keyb_special',2), t.key('SPACE')
local pause, mute, escape = t.key('P'), t.key('M'), t.key('ESC')
local function launch()
    space:set_value(1); shift:set_value(1); t.ticks(2)
    space:set_value(0); shift:set_value(0); t.ticks(2)
end
local function fixture(x,y,dx,dy)
    t.settle()
    t.write('state',2); t.write('drawn',0); t.write('ball_x',x); t.write('ball_y',y)
    t.write('dx',dx); t.write('dy',dy); t.write('x_phase',2); t.write('speed',1)
    t.write('paddle_x',100)
end
t.run(function()
    t.tap(space)
    t.check(t.read('state') == 1 and t.read('remaining') == 60 and t.read('lives') == 3, 'start creates sixty bricks and three lives')
    left:set_value(1); t.ticks(50); left:set_value(0)
    t.check(t.read('paddle_x') == 14 and t.read('ball_x') == 26, 'held left clamps paddle and carries the waiting ball')
    right:set_value(1); t.ticks(65); right:set_value(0)
    t.check(t.read('paddle_x') == 224 and t.read('ball_x') == 236, 'held right clamps without wrapping')
    launch()
    t.check(t.read('state') == 2 and t.read('ball_y') < 164, 'mapped Space launches on press')
    local prompt_row = 0x2000 + 7*1024 + 80
    t.check(t.mem:read_u8(prompt_row + 32) == 0, 'launch clears the entire serve prompt')
    if t.smoke then return end
    -- Follow the ball using only the same hardware modifier inputs as a player.
    for _ = 1, 1000 do
        if t.read('state') ~= 2 or t.read('remaining') <= 54 then break end
        local delta = t.read('ball_x') - (t.read('paddle_x') + 12)
        left:set_value(delta < -3 and 1 or 0); right:set_value(delta > 3 and 1 or 0)
        t.ticks(1)
    end
    left:set_value(0); right:set_value(0)
    t.check(t.long('score') > 0 and t.read('remaining') < 60, 'input-only play rebounds and destroys real bricks')
    t.check(t.long('best') == t.long('score') and t.edges > 0, 'scoring updates best and generates speaker effects')
    t.snapshot('gameplay')
    t.tap(pause)
    t.check(t.read('state') == 3, 'P pauses the rally')
    local pixels, x, y = t.pixels(), t.read('ball_x'), t.read('ball_y')
    left:set_value(1); t.ticks(35); left:set_value(0)
    t.check(t.read('ball_x') == x and t.read('ball_y') == y and pixels == t.pixels(), 'pause freezes physics and framebuffer')
    t.tap(pause); t.check(t.read('state') == 2, 'P resumes the rally')
    fixture(14,120,-3,1); t.ticks(1)
    t.check(t.read('dx') == 3 and t.read('ball_x') >= 14, 'left wall reflects without underflow')
    fixture(248,120,3,1); t.ticks(1)
    t.check(t.read('dx') == 253 and t.read('ball_x') <= 248, 'right wall reflects without overflow')
    fixture(150,28,1,-1); t.ticks(1)
    t.check(t.read('dy') == 1 and t.read('ball_y') >= 28, 'ceiling reflects the ball')
    fixture(102,166,1,1); t.ticks(1)
    t.check(t.read('dy') == 255 and t.read('dx') == 253, 'left paddle edge steers left')
    fixture(122,166,1,1); t.ticks(1)
    t.check(t.read('dy') == 255 and t.read('dx') == 3, 'right paddle edge steers right')
    fixture(35,103,1,-1); t.array('bricks',50,1); t.write('remaining',60)
    local score = t.long('score'); t.ticks(1)
    t.check(t.array('bricks',50) == 0 and t.long('score') == score+10 and t.read('dy') == 1, 'bottom-row contact removes a brick, scores and reflects')
    fixture(35,43,1,-1); t.array('bricks',0,2)
    score = t.long('score'); t.ticks(1)
    t.check(t.array('bricks',0) == 1 and t.long('score') == score, 'armored brick takes its first hit without disappearing')
    fixture(35,43,1,-1); t.ticks(1)
    t.check(t.array('bricks',0) == 0 and t.long('score') == score+60, 'second armor hit awards the higher row value')
    fixture(35,103,1,-1); t.array('bricks',50,1); t.writelong('score',999995); t.ticks(1)
    t.check(t.long('score') == 999999, 'score saturates rather than wrapping')
    t.ticks(15); t.tap(mute); t.check(t.read('muted') == 1, 'M mutes sound')
    local edges = t.edges
    fixture(35,103,1,-1); t.array('bricks',50,1); t.ticks(1)
    t.check(t.edges == edges, 'muted brick impacts generate no speaker toggles')
    t.ticks(15); t.tap(mute); t.check(t.read('muted') == 0, 'M restores sound')
    fixture(20,180,1,1); t.write('lives',3); t.ticks(1)
    t.check(t.read('state') == 1 and t.read('lives') == 2 and t.read('ball_y') == 164, 'miss costs one life and waits for a new serve')
    fixture(20,180,1,1); t.write('lives',1); t.ticks(1)
    t.check(t.read('state') == 4 and t.read('lives') == 0, 'last miss ends the game')
    t.ticks(50); t.tap(space)
    t.check(t.read('state') == 1 and t.read('lives') == 3 and t.long('score') == 0 and t.long('best') == 999999, 'retry resets the wall and preserves best score')
    fixture(35,103,1,-1)
    for i = 0, 59 do t.array('bricks',i,0) end
    t.array('bricks',50,1); t.write('remaining',1); t.ticks(1)
    t.check(t.read('state') == 5 and t.read('remaining') == 0, 'last brick completes the stage')
    t.ticks(95)
    t.check(t.read('state') == 1 and t.read('wave') == 2 and t.read('remaining') == 60 and t.array('bricks',0) == 2, 'next stage restores the wall with armored top bricks')
    t.write('wave',98); t.write('transition_timer',0); t.write('state',5); t.ticks(1)
    t.check(t.read('wave') == 99 and t.read('speed') == 5, 'late-stage speed is capped at five collision substeps')
    t.tap(escape); t.check(t.read('state') == 0, 'Escape returns to title')
    t.integrity()
end)
