#!/usr/bin/env python3
"""Pack a five-letter lexicon as per-initial, base-26 delta/LEB128 streams."""
from pathlib import Path
from math import gcd
import sys


def read_words(path: Path) -> list[str]:
    words = path.read_text().splitlines()
    if not words or len(set(words)) != len(words) or any(
        len(w) != 5 or not w.isascii() or not w.isalpha() or w != w.upper() for w in words
    ):
        raise ValueError(f"{path}: expected unique five-letter uppercase words")
    return words


def pack(words: list[str]) -> tuple[list[int], bytes]:
    offsets, data = [], bytearray()
    for initial in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
        offsets.append(len(data))
        previous = 0
        for word in sorted(w for w in words if w[0] == initial):
            value = 0
            for ch in word[1:]:
                value = value * 26 + ord(ch) - ord('A')
            delta, previous = value - previous, value
            while delta >= 128:
                data.append((delta & 127) | 128)
                delta >>= 7
            data.append(delta)
    offsets.append(len(data))
    return offsets, bytes(data)


def compile_words(source: Path, answers: Path, output: Path) -> None:
    words, choices = read_words(source), read_words(answers)
    if not set(choices) <= set(words):
        raise ValueError('Answers missing from dictionary: ' + ', '.join(sorted(set(choices) - set(words))))
    if gcd(73, len(choices)) != 1 or len(choices) > 897:
        raise ValueError('Answer count must be <= 897 and coprime with puzzle multiplier 73')
    offsets, data = pack(words)
    lines = ['/* Generated by tools/wordlist.py; source license: games/wordle/WORDLIST-LICENSE.txt. */',
             f'#define ANSWER_COUNT {len(choices)}', f'#define WORD_COUNT {len(words)}',
             'static const uint16_t dict_offsets[27] = {' + ','.join(map(str, offsets)) + '};',
             'static const uint8_t dictionary[] = {']
    lines += [','.join(map(str, data[i:i+24])) + ',' for i in range(0, len(data), 24)]
    lines += ['};', 'static const uint16_t answer_codes[ANSWER_COUNT] = {']
    for word in choices:
        group = sorted(w for w in words if w[0] == word[0])
        index = group.index(word)
        if index >= 2048:
            raise ValueError('Initial-letter bucket exceeds 11-bit answer index')
        lines.append(str(((ord(word[0])-65) << 11) | index) + 'U,')
    lines += ['};']
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text('\n'.join(lines) + '\n')
    (output.parent / 'WORDLIST-LICENSE.txt').write_text((source.parent / 'WORDLIST-LICENSE.txt').read_text())
    print(f'Word Five: {len(words)} accepted words in {len(data)} bytes; {len(choices)} answers')


if __name__ == '__main__':
    compile_words(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
